### ISSUE TITLE
Ability to close menu when using anchor links

### ISSUE THREAD

**Issue by richardwiggins** [CodyHouse/cd-responsive-sidebar-changelog#1]
I'm using this component (slightly modified) but I have several anchor links. When on mobile clicking an an anchor link won't close the menu so I somehow need the ability to do this.

Started looking at the JS but got a little stuck.

**Comment by claudia-romano** [comment]
Hi there, you can add the `.js-sidebar__close-btn` class to your links. That should fix your issue. Cheers!

**Comment by richardwiggins** [comment]
Hey, that does close the nav so thanks, but it's preventing the default action of the link too, so the anchor link doesn't work. Any ideas?

**Comment by richardwiggins** [comment]
I've taken out `event.preventDefault();` for `.js-sidebar__close-btn` which has sorted it 👍

**Comment by richardwiggins** [comment]
Actually, I'm still having an issue with this as I need for a link which sits alongside the `sidebar` open/close menu button within `nav__mobile` to also close the menu and go to an anchor link. Using `.js-sidebar__close-btn` doesn't work here.

**Comment by richardwiggins** [comment]
Found a workaround for now, not pretty but it works.
