### ISSUE TITLE
Customised version but sidebar--static is being fired by default on mobile

### ISSUE THREAD

**Issue by richardwiggins** [CodyHouse/cd-responsive-sidebar-changelog#2]
On mobile, `sidebar--static` is being applied to `aside` on-load. This is causing issues when I open my menu. If I scroll at all or change the orientation `sidebar--static` does get removed and then the menu works as expected.

This is only an issue on physical mobile devices (only testing on iPhone 8 and X), it doesn't occur when using mobile view/dev tools on desktop browsers.

I don't understand JS well enough to figure out your code. Any ideas why this is being fired?

I've done quite a bit of customisation but nothing I can see that would cause this.

Live version: https://preview.mkgeeknight.co.uk

**Comment by richardwiggins** [comment]
I have reverted back to an almost barebones install now with your latest original css, js and html and it appears to be an issue in the default component.

**Comment by claudia-romano** [comment]
Hi there,
we have just pushed an updated version of the component that fixes the issue (tested on iOS 13). Cheers!

**Comment by richardwiggins** [comment]
Thanks. I'll take a look 👍

**Comment by richardwiggins** [comment]
Has this been pushed to https://codyhouse.co/ds/components/info/responsive-sidebar or is it on Github somewhere?

Is there any details on the change? Wondering if it was just a JS change?

**Comment by sebastiano-guerriero** [comment]
It has been pushed to https://codyhouse.co/ds/components/info/responsive-sidebar (JS changes only)

**Comment by richardwiggins** [comment]
Thanks. Integrated and live 🥳  - https://mkgeeknight.co.uk

**Comment by sebastiano-guerriero** [comment]
WOW, love the site!
