### ISSUE TITLE
Potential bug around getComputedStyle

### ISSUE THREAD

**Issue by richardwiggins** [CodyHouse/cd-responsive-sidebar-changelog#3]
There seems to be a bug in this which is linked to [this issue](https://github.com/CodyHouse/cd-responsive-sidebar-changelog/issues/2) as well.

On Safari desktop and on mobile versions, `getComputedStyle` is firing the `static` version at small screen sizes when it should be firing `mobile`. Chrome is working correctly.

**Comment by claudia-romano** [comment]
This appears to be a duplicate of https://github.com/CodyHouse/cd-responsive-sidebar-changelog/issues/2.
