### ISSUE TITLE
Suggestion - Dynamic Sticky Sidebar

### ISSUE THREAD

**Issue by YannickMol** [CodyHouse/cd-responsive-sidebar-changelog#4]
Hi Team,

I love the component that you built and have one suggestion to improve it.
Could it become dynamic, so that it always shows the entire sidebar and if there is too much content inside it, it will overflow with a scrollbar? Idea is coming from [https://codepen.io/hexagoncircle/pen/oNLZmvV](https://codepen.io/hexagoncircle/pen/oNLZmvV). 

Let me know what you think!

Regards,
Yannick

**Comment by sebastiano-guerriero** [comment]
Hi Yannick! There's the the --sticky-on-desktop variation that behaves like the linked example: 
https://codyhouse.co/ds/components/app/responsive-sidebar--sticky-on-desktop

**Comment by YannickMol** [comment]
Hi! Thanks for the reply. This variation doesn't cover entirely what I mean. In your variation the sidebar has a fixed height, whereas the sidebar in the codepen has a dynamic height, which will overflow if the content inside is too high for the sidebar container. Is this something that is easy to achieve in your component?

**Comment by sebastiano-guerriero** [comment]
oh, gotcha! To achieve the same result using our component, add the `.items-start@md` utility class to the grid container of the `<aside>`.

```html
<div class="grid gap-md@md items-start@md"> <!-- 👈 -->
  <aside><!-- ... --></aside>
  <main><!-- ... --></main>
</div>
```
