### ISSUE TITLE
Prevent the underlying content from scrolling

### ISSUE THREAD

**Issue by dariopetraroia** [CodyHouse/cd-responsive-sidebar-changelog#5]
Hy can you add like in the modal component: data-modal-prevent-scroll="body"

to prevent the underlying content from scrolling while the sidebar is open.

this should be useful also in the drawer component.

**Comment by claudia-romano** [comment]
Hi Dario, thanks for the suggestion. We have updated both components.
You can check the [Info page](https://codyhouse.co/ds/components/info/responsive-sidebar#overflow) for additional details.
